name: Python Tests

on: [push, pull_request]  # Run on pushes and pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Replace '3.x' with your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fredapi pytest pandas python-dotenv

    - name: Set environment variable
      run: |
        echo "API_KEY=${{ secrets.FRED_API_KEY }}" >> $GITHUB_ENV  # FRED_API_KEY from repo secrets

    - name: Run Tests
      run: pytest
